# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog, QDialogButtonBox
from Automatic_Page_Turner import MainWindow
import os


class DialogWindow(QDialog):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Please choose your setting")
        self.resize(652, 482)

        self.gridLayout = QtWidgets.QGridLayout()

        self.buttonBox = QDialogButtonBox()
        self.buttonBox.setGeometry(QtCore.QRect(270, 430, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.button(QDialogButtonBox.Ok).setText("Start Tracking")
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.buttonBox.accepted.connect(self.open_main_window)

        self.gridLayout.addWidget(self.buttonBox, 9, 4, 1, 1)

        self.piece_label = QtWidgets.QLabel("Piece", self)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.piece_label.setFont(font)
        self.gridLayout.addWidget(self.piece_label, 0, 0, 1, 1)

        self.audio_layout = QtWidgets.QVBoxLayout()
        self.audio_label = QtWidgets.QLabel("Audio", self)
        font = QtGui.QFont()
        font.setBold(True)
        self.audio_label.setFont(font)
        self.audio_label.setAlignment(QtCore.Qt.AlignCenter)
        self.audio_layout.addWidget(self.audio_label)
        self.audio_dropdown = QtWidgets.QComboBox()
        self.audio_dropdown.addItem("live")
        self.audio_dropdown.addItem("choose from library")
        self.audio_layout.addWidget(self.audio_dropdown)
        self.gridLayout.addLayout(self.audio_layout, 0, 2, 2, 1)

        self.score_layout = QtWidgets.QVBoxLayout()
        self.score_label = QtWidgets.QLabel("Score", self)
        font = QtGui.QFont()
        font.setBold(True)
        self.score_label.setFont(font)
        self.score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.score_layout.addWidget(self.score_label)
        self.score_dropdown = QtWidgets.QComboBox()
        self.score_dropdown.addItem("live")
        self.score_dropdown.addItem("choose from library")
        self.score_layout.addWidget(self.score_dropdown)
        self.gridLayout.addLayout(self.score_layout, 0, 4, 2, 1)

        self.view_label = QtWidgets.QLabel("View", self)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.view_label.setFont(font)
        self.view_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.view_label, 3, 0, 1, 1)

        self.view_prediction_layout = QtWidgets.QVBoxLayout()
        self.prediction_label = QtWidgets.QLabel("Prediction", self)
        font = QtGui.QFont()
        font.setBold(True)
        self.prediction_label.setFont(font)
        self.view_prediction_layout.addWidget(self.prediction_label)
        self.prediction_note_box = QtWidgets.QCheckBox("&note level")
        self.view_prediction_layout.addWidget(self.prediction_note_box)
        self.prediction_bar_box = QtWidgets.QCheckBox("&bar level")
        self.view_prediction_layout.addWidget(self.prediction_bar_box)
        self.prediction_system_box = QtWidgets.QCheckBox("&system level")
        self.view_prediction_layout.addWidget(self.prediction_system_box)
        self.gridLayout.addLayout(self.view_prediction_layout, 3, 4, 2, 1)

        self.ground_truth_layout = QtWidgets.QVBoxLayout()
        self.ground_truth_label = QtWidgets.QLabel("Ground Truth", self)
        font = QtGui.QFont()
        font.setBold(True)
        self.ground_truth_label.setFont(font)
        self.ground_truth_layout.addWidget(self.ground_truth_label)
        self.gtruth_note_box = QtWidgets.QCheckBox("&note level")
        self.ground_truth_layout.addWidget(self.gtruth_note_box)
        self.gtruth_bar_box = QtWidgets.QCheckBox("&bar level")
        self.ground_truth_layout.addWidget(self.gtruth_bar_box)
        self.gtruth_system_box = QtWidgets.QCheckBox("&system level")
        self.ground_truth_layout.addWidget(self.gtruth_system_box)
        self.gridLayout.addLayout(self.ground_truth_layout, 3, 2, 2, 1)

        self.model_label = QtWidgets.QLabel("Model", self)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.model_label.setFont(font)
        self.model_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.model_label, 6, 0, 1, 1)

        self.model_dropdown = QtWidgets.QComboBox()
        self.model_dropdown.addItem("default")
        self.model_dropdown.addItem("choose local")
        self.gridLayout.addWidget(self.model_dropdown, 6, 2, 1, 1)

        self.setLayout(self.gridLayout)

        ##################################################################
        # this contains all spacers to keep the correct layout
        piece_view_spacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum,
                                                  QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(piece_view_spacer, 1, 0, 2, 1)
        view_model_spacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum,
                                                  QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(view_model_spacer, 4, 0, 2, 1)

        column1_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                               QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(column1_spacer, 1, 1, 1, 1)

        audio_gt_spacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum,
                                                QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(audio_gt_spacer, 2, 2, 1, 1)

        gt_model_dropd_spacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                      QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(gt_model_dropd_spacer, 5, 2, 1, 1)

        column2_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                               QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(column2_spacer, 0, 3, 1, 1)

        score_pred_spacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum,
                                                  QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(score_pred_spacer, 2, 4, 1, 1)

        input_button_spacer = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum,
                                                    QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(input_button_spacer, 7, 0, 2, 1)
        ##################################################################

        self.audio_path = None
        self.score_path = None
        self.model_path = os.path.join('..', 'models', 'test_model', 'best_model.pt')
        self.default_path = os.path.join('..', 'demo_piece')
        self.audio_dropdown.activated[str].connect(self.react_to_audio_dropdown)
        self.score_dropdown.activated[str].connect(self.react_to_score_dropdown)
        self.model_dropdown.activated[str].connect(self.react_to_model_dropdown)

    def open_main_window(self):
        prediction_box_states = [self.prediction_note_box.isChecked(), self.prediction_bar_box.isChecked(),
                                 self.prediction_system_box.isChecked()]
        ground_truth_box_states = [self.gtruth_note_box.isChecked(), self.gtruth_bar_box.isChecked(),
                                 self.gtruth_system_box.isChecked()]
        self.window = MainWindow(self.audio_path, self.score_path, self.model_path, ground_truth_box_states,
                            prediction_box_states)
        self.window.show()
        # self.window.create_prediction_object()
        self.window.exec_()

    def react_to_audio_dropdown(self, text):
        if text == "choose from library":
            self.choose_piece_dir("wav")

    def react_to_score_dropdown(self, text):
        if text == "choose from library":
            self.choose_piece_dir("npz")

    def react_to_model_dropdown(self, text):
        if text == "choose local":
            self.choose_piece_dir("pt", os.path.join('..', 'models'))
        else:
            self.model_path = os.path.join('..', 'models', 'test_model', 'best_model.pt')

    def choose_piece_dir(self, extension, path=None):
        if path is not None:
            search_path = path
        else:
            search_path = self.default_path
        curr_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, 'Select one piece', search_path,
                                                             f"(*.{extension})",
                                                             options=QFileDialog.DontUseNativeDialog)
        if extension == "wav":
            self.audio_path = curr_path
        elif extension == "npz":
            self.score_path = curr_path
        elif extension == "pt":
            self.model_path = curr_path

        print(curr_path)


if __name__ == "__main__":
    app = QApplication([])
    window = DialogWindow()
    window.show()
    app.exec()

